### ISSUE TITLE
BUG DataFrameETL fails with int-like Categoricals

### ISSUE THREAD

**Issue by stephen-hoover** [civisanalytics/civisml-extensions#18]
The following fails under v0.1.5 (the most recent release):

```python
    raw = pd.concat([
        pd.Series([1.0, np.NaN, 3.0], dtype='float', name='fruits'),
        pd.Series([500, 1000, 1000], dtype='category', name='intcat'),
    ], axis=1)
    expander = DataFrameETL(cols_to_expand='auto', dummy_na=True)
    tfm = expander.fit_transform(raw)
```

The error is "ValueError: fill value must be in categories".

It looks like this is due to `DataFrameETL._flag_numeric` incorrectly marking a `pd.Categorical` as "numeric" when every level happens to be an integer.

**Comment by beckermr** [comment]
Hmmmm. This feels more like a pandas API error. Why would one want to restrict fill values to be in the categories you already have? The fact that the column is numeric is a correct inference on the part of the transformer.

**Comment by beckermr** [comment]
Whoops sorry!

**Comment by beckermr** [comment]
Apparently pandas wants you to add the category first. https://stackoverflow.com/questions/32718639/pandas-filling-nans-in-categorical-data

**Comment by beckermr** [comment]
I would prefer to include logic around how to fill NaNs in columns with category dtypes as opposed to flagging all numeric categories as objects instead of numeric.
